woowacourse/tecoble

- optional_vs_null.md
> [둔덩] null 반환보단 Optional을 활용하자.

- _posts/2020-05-07-appropriate_method_for_test_by_parameter.md
> [스티치] 메서드 시그니처를 수정하여 테스트하기 좋은 메서드로 만들기 - 오타 수정

- _posts/2020-04-26-Method-Naming.md
> [티거] Method Naming 테이블 명 수정

- _posts/2020-05-18-ArrayList-vs-Arrays.asList.md
> [티거] new ArrayList() vs Arrays.asList()

- _posts/2020-05-17-appropriate_method_for_test_by_interface.md
> [스티치] 인터페이스를 분리하여 테스트하기 좋은 메서드로 만들기

- _posts/2020-04-21-optional-vs-null.md
- _posts/2020-05-07-avoid-hard-coding.md
- _posts/2020-05-18-inheritance-vs-composition.md
> [둔덩] 태그 및 댓글 추가

- _posts/2020-05-18-immutable-object.md
> [카일] 불변객체의 정의와 생성하는 방법

- _posts/2020-04-21-enum_search.md
- _posts/2020-04-30-iteration_vs_recursion.md
- _posts/2020-05-10-single-job-method.md
> [보스독] comment tags refactoring

- _posts/2020-04-24-variable_naming.md
- _posts/2020-04-28-ask-instead-of-getter.md
> [오렌지] 태그, 댓글 추가

- _posts/2020-04-21-optional-vs-null.md
- _tags/composition.html
- _tags/hard-codding.html
- _tags/inheritance.html
- _tags/optional.html
> [둔덩] 태그 html 추가

- _posts/2020-04-24-one-test-must-check-one-scenario.md
- _posts/2020-05-07-appropriate_method_for_test_by_parameter.md
- _posts/2020-05-17-appropriate_method_for_test_by_interface.md
> [스티치] 태그 및 댓글 기능 설정

- _tags/functional-programming.html
> [오렌지] tag html 추가

- _posts/2020-05-14-foreach-vs-forloop.md
> [오렌지] foreach-vs-forloop 예시코드 수정

- _posts/2020-06-02-law-of-demeter.md
Fixes #75
많은 지적 부탁드립니다!
코로나 조심하세요 ~~ : )
> [둔덩] 디미터 법칙(Law of Demeter)

- _posts/2020-06-10-one-level-of-indentation-per-method.md
> [티거] 한 메서드에 오직 한 단계의 들여쓰기만 한다.

- _posts/2020-07-18-cors.md
> [카일] cors에 대해서 알아보자.

- _posts/2020-07-28-global-exception-handler.md
> [티거] Global Exception Handler

- _includes/head.html
- feed.xml
RSS를 추가해두면 알람을 원하는 분들이 RSS 리더를 통해 알람 설정만 하면 된다고 합니다!
fixes #150
> [둔덩] RSS 추가

- _posts/2020-07-29-equals-and-hashCode.md
- _posts/2020-08-19-rest-assured-vs-mock-mvc.md
초안이라 부족한 부분이 많습니다ㅠㅠ
많이많이 지적해주세요!
fixes #149
> [둔덩] MockMvc VS RestAssured

- _posts/2020-07-31-solid-1.md
예제를 선택하는게 참 어렵네요...ㅜㅜ 리뷰 부탁드립니다!
close #71
> [카일] SOLID원칙

- _posts/2020-08-17-put-vs-patch.md
author 입력 양식이 잘못되어 머릿말 부분 수정합니다.
> fix header of #167

- _posts/2020-09-29-spring-properties-binding.md
[글](https://github.com/woowacourse/javable/blob/doc%2Fspring-properties-binding/_posts/2020-09-29-spring-properties-binding.md)
제목에 properties를 application.properties로 바꿔야할까요?
close #216
> [비밥] Spring Boot 에서 properties 값 주입받기

- _posts/2020-08-31-entity-lifecycle-1.md
기존 글에서 단어가 부자연스러운 부분이 있어 수정하였습니다.
> [라테] Entity Lifecycle을 고려해 코드를 작성하자 1편 - 단어 및 문장 수정

- _posts/2020-08-18-spring-rest-docs.md
> [티거] Spring REST Docs에 toc: true 추가

- _posts/2020-09-20-test-refactor-generic.md
> [카일] 제네릭을 통해 테스트 중복을 제거해보자! 

- _posts/2020-11-03-osiv_with_interceptor.md
> [카일] Custom Interceptor와 OSIV를 함께 사용할 때 유의점

- _posts/2020-11-03-assertJ_methods.md
> [카일] AssertJ의 다양한 메소드를 활용해보자.

- .github/workflows/gatsby-build.yml
> [스티치] github action에 gatsby build 스크립트 작성

- .github/workflows/gatsby-build.yml
> [스티치] github action에 gatsby build 스크립트 수정

- _posts/2020-10-27-polymorphism.md
fixes #246 
초심을 잃지말자는 취지에서 객체지향 관련 글을 한편 올려봅니다.
> [보스독] 다형성이란?

- src/content/post/2020-08-17-custom-exception.md
UnsupportedOperationExceptio -> UnsupportedOperationException
> fix: 오타 수정

- src/content/post/2021-06-18-spring-request-mapping.md
'@제목' 과 같은 형식으로 따옴표 안에 정보를 보냄으로 해결
현재 build가 터지는 상황이라 빠른 머지 부탁드려요!
> [완태] title을 @로 시작했을 때 build 되지 않는 문제 해결

- package.json
name과 homepage 값 업데이트 했습니다
name: Javable -> Tecoble
homepage: https://woowacourse.github.io/javable/ -> https://woowacourse.github.io/tecoble/
> package.json 업데이트

- src/content/post/2021-05-17-constructor.md
작성자 prefix 추가 이전에 PR 날려진 글에 3기_ 추가되었는지 확인 필요
> hotfix: 작성자에 prefix 추가되지 않은 문제 해결

- src/website-config.ts
> [파피] 오픈 그래프 지원 미숙 Issue(#396) 해결

- src/templates/post.tsx
배포 환경에서 확인할 수밖에 없어서 많은 PR 양해 부탁드립니다..😭 이건 셀프머지 하고 확인할게요..다니 미안해요..
> [파피] 오픈 그래프 지원 미숙 Issue(#396) og:url tecoble 단어 중복 수정

- src/content/post/2021-07-15-git-branch.md
git 브랜치 전략에 대해서 작성해보았습니다!
잘못된 내용이나 이해가 잘 안되는 내용 있으면 마구마구 지적해주세요 :)
감사합니다~
> [샐리] git 브랜치 전략에 대해서

- src/content/post/2021-06-25-dispatcherservlet-part-1.md
- src/content/post/2021-07-15-dispatcherservlet-part-2.md
> [다니] DispatcherServlet - Part 2

- README.md
README 파일을 작성해보았습니다. 테코블이 오픈 소스가 아닌 점을 고려하여 여러 내용을 삽입하기 보다는 소개 위주의 단락으로만 구성해보았습니다. 혹시 수정하거나 추가했으면 하는 사항이 있다면 언제든 이야기 부탁드려요!
<br/>
Close #415
> [카일] README.md 작성

- src/content/post/2021-08-15-jpa-cascadetype-remove-vs-orphanremoval-true.md
- src/content/post/2021-08-15-jpa-remove-vs-orphanremoval.md
<br/>
케빈, 와일더, 와이비 잘 부탁드립니다 ~! 🙇‍♀️
<br/>
Close #502
> [다니] JPA CascadeType.REMOVE vs orphanRemoval = true

- static/CNAME
- [[블로그] 개츠비(Gatsby) + Github로 블로그 서비스 하기 - Part III](https://richwind.co.kr/166)
- [GitHub Pages 도메인 네임 설정 하기
](http://saltfactory.github.io/github/setting-domain-name-in-github-pages-via-cname.html)
> [다니] CNAME 파일 설정

- src/content/post/2021-04-25-dto-layer-scope.md
이거 이후로도 나오면 명령어 이용해서 걸러보겠습니다..
> fix: 유효하지 않은 utf-8 문자 제거

- src/content/post/2021-09-03-hierarchy-data-with-rdb.md
예제 코드에서 미처 발견하지 못한 오탈자가 존재해 수정합니다.
Close #543
> [케빈] 관계형 DB에서 계층적인 데이터 관리하기 오탈자 수정

- src/content/post/2021-09-05-web-socket-practice.md
<br/>
우선 늦어서 죄송합니다 ㅎㅎ..
처음 보는 독자에게도 내용 전달이 잘 될지 확신이 없는데, 많은 피드백 부탁드립니다! 시간 내주셔서 감사합니다🙏
<br/>
Close #541
> [파피] 웹 소켓에 대해 알아보자! - 실전 편

- src/components/PostContent.tsx
- src/layouts/index.tsx
Close #394 
selection(본문 혹은 코드 스니펫 드래그)을 하면 글이 잘 보이지 않는 문제 해결
불필요한 selection관련 css 제거
> selection 상황에 코드 스니펫 가독성 문제 해결

- src/content/post/2021-11-10-web-socket-test.md
<br/>
바쁜시간 내주셔서 감사합니다!! 🙏🙏🙏
<br/>
Close #639
> [와일더] 웹 소켓에 대해 알아보자! - 테스트 편

- src/content/post/2021-11-21-dip.md
> [케빈] DIP : 변경에 유연하고 테스트하기 좋은 코드 설계

- src/content/author.yaml
<br/>
https://github.com/woowacourse/tecoble/pull/691 PR을 날렸으나 파일 확장자가 맞지 않아 run fail이 난 것 같습니다.
확장자 명을 변경하여 다시 merge 해보는 브랜치입니다. 
<br/>
Close #{이슈_번호}
> [이스트, 토르] - 반정규화를 통한 좋아요 개수 조회 최적화

- src/content/post/2022-09-26-life-of-pixel.md
<br/>
`draft` 상태를 `true`에서 `false`로 변경한 후 재업로드 합니다.
> [병민] - Life of Pixel 재업로드 

- src/content/post/2022-09-26-life-of-pixel.md
<br/>
post 형식에서 `date` 오타를 수정합니다.
> [병민] - Life of Pixel 재업로드

- src/content/post/2022-10-17-jpa-hibernate-proxy.md
> [오찌] 오찌 요청으로 인한 내용 수정

- src/content/post/2022-10-10-like-count.md
> [토르, 이스트] 토르, 이스트 글 이미지 수정

- src/content/post/2022-10-15-function-overloading.md
> [시지프] 타스 이미지 중복 제거

- src/content/post/2022-10-22-slack-login-and-alarm.md
> 테코블에서 정상 동작하도록 수정

- src/content/author.yaml
> fix: author.yaml에 기존 4기 크루 추가

- src/content/post/2022-10-24-openID-Oauth.md
- src/content/post/2022-11-07-mysql-isolation.md
* 쿼리치 글 썸네일 수정
* 써머 포스팅에 중복된 이미지 수정
> 쿼리치, 써머 이미지 수정

- src/content/author.yaml
author.yaml 파일 오타 수정
<br/>
<br/>
Close #{이슈_번호}
> [제로] 빌드 오류 수정

- src/content/post/2023-08-16-concurrency-managing.md
`@Component` 어노테이션 부재로 예시 코드 실행이 정상적으로 되지 않는 문제를 해결합니다.
> [애쉬] 선착순 티켓 예매의 동시성 문제 - 코드 오류 수정

- src/content/post/2023-10-11-marker-rendering-optimization.md
센트의 글, 'useLayoutEffect를 활용한 산발적 마커 렌더링 최적화'의 발행일자를 수정하였습니다.
> [센트] 발행일자 수정

- src/content/post/2023-10-25-HISTORY-OF-WEB-APP.md
<br/>
이미지 로딩 오류에 따른 이미지 링크 소스 수정
<br/>
Close #{이슈_번호}
> [테오] 웹어플리케이션의 역사 포스팅 이미지 소스 링크 수정

- src/content/post/2023-10-25-HISTORY-OF-WEB-APP.md
<br/>
타이틀이 중복되는 문제 수정 및 레퍼런스 항목에 불릿 추가
<br/>
Close #{이슈_번호}
> [테오] 중복 타이틀 제거 및 레퍼런스 수정
